# fly.toml app configuration file generated for mahdiye-1x96wq on 2026-05-21T13:09:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mahdiye-1x96wq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '4s'
    grace_period = '5s'
    method = 'get'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
